services:
  bffpgc:
    image: bffpgc
    container_name: bffpgc
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - be-network 
networks:
  be-network:
    driver: bridge
    external: true